Adding debug step to see if any allure files were created

diff --git a/.github/workflows/api-test.yml b/.github/workflows/api-test.yml
--- a/.github/workflows/api-test.yml
+++ b/.github/workflows/api-test.yml
@@ -34,6 +34,10 @@ jobs:
       - name: Run API Tests
         run: newman run "TMDB_API_Tests.postman_collection.json" --environment TMDB.postman_environment.json --env-var "api_key=${{ secrets.TMDB_API_KEY }}" --env-var "base_url=https://api.themoviedb.org/3" --reporters cli,htmlextra,allure --reporter-htmlextra-export reports/test-report.html --reporter-allure-export allure-results
 
+      - name: Check Allure Results
+        run: ls -la allure-results || echo "allure-results folder not found"
+        if: always()
+      
       - name: Run API Mock Tests
         run: newman run "TMDB_API_Tests_Mock_Server.postman_collection.json" --environment TMDB_Mock_Server.postman_environment.json --env-var "api_key=${{ secrets.TMDB_API_KEY }}" --env-var "base_url=https://6cd6cc6f-9516-431b-bebb-a37a90e7421f.mock.pstmn.io" --reporters cli,htmlextra,allure --reporter-htmlextra-export reports/test-report-mock.html --reporter-allure-export allure-results-mock
 
